-- Migration: generated_sections table for chunked code generation
-- This table stores individual section components that are later assembled into pages

CREATE TABLE IF NOT EXISTS generated_sections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    pipeline_run_id UUID NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
    page_slug TEXT NOT NULL,
    section_index INTEGER NOT NULL,
    section_type TEXT NOT NULL,
    component_name TEXT NOT NULL,
    component_code TEXT NOT NULL,
    imports TEXT[] DEFAULT '{}',
    props JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Unique constraint: one section per page per index per pipeline
    UNIQUE(pipeline_run_id, page_slug, section_index)
);

-- Index for fast lookups during assembly
CREATE INDEX idx_generated_sections_lookup 
    ON generated_sections(pipeline_run_id, page_slug);

-- Index for counting completion status
CREATE INDEX idx_generated_sections_pipeline 
    ON generated_sections(pipeline_run_id);

-- Comment
COMMENT ON TABLE generated_sections IS 'Stores individual React section components generated by section-generator agents, later assembled by assembly agent';
